name: Build and Push to GHCR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:demo

  kcs-scan:
    needs: build-and-push
    runs-on: self-hosted
    container:
      image: repo.kcs.kaspersky.com/images/scanner:v2.0.0-with-db
      credentials:
        username: ${{ secrets.KCS_REPO_USER }}
        password: ${{ secrets.KCS_REPO_PASS }}

    steps:
      - name: Scan image with KCS
        env:
          SCAN_TARGET: ghcr.io/borasevin/kcs-ghcr-demo:demo
          API_TOKEN: ${{ secrets.KCS_API_TOKEN }}
          API_BASE_URL: http://kcs.local
          COMPANY_EXT_REGISTRY_USERNAME: borasevin
          COMPANY_EXT_REGISTRY_PASSWORD: ${{ secrets.GHCR_PAT }}
        run: /bin/sh /entrypoint.sh $SCAN_TARGET --stdout > kcs-scan-result.json
