name: Build and Push to Local Registry

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t localhost:5000/kcs-ghcr-demo:demo .

      - name: Push image
        run: docker push localhost:5000/kcs-ghcr-demo:demo
